version: '3'
services:
  app:
    build: .
    ports:
     - "8080:8080"
    links:
      - redis
  redis:
    image: redis
    volumes:
      - data:/data
    ports:
     - "6379:6379"

volumes:
  data: